// data/brandProducts.js
export const brandProducts = {
    samsung: [
        { id: 1, name: 'Samsung Galaxy S21', image: '/Images/samsunggalaxys21.png', price: '$799', rating: 4.5 },
        { id: 2, name: 'Samsung Galaxy Note 20', image: '/Images/samnote20.jpeg', price: '$999', rating: 4.4 },
        { id: 3, name: 'Samsung Galaxy Z Fold 3', image: '/Images/z fold.jpeg', price: '$1799', rating: 4.7 },
        { id: 4, name: 'Samsung Galaxy A52', image: '/Images/a52.jpeg', price: '$499', rating: 4.2 },
        { id: 5, name: 'Samsung Galaxy A72', image: '/Images/a72sma.jpeg', price: '$599', rating: 4.3 },
        { id: 6, name: 'Samsung Galaxy Watch 4', image: '/Images/watchh.jpeg', price: '$249', rating: 4.1 },
        { id: 7, name: 'Samsung 1TB SSD', image: '/Images/ssb.jpeg', price: '$129', rating: 4.6 },
        { id: 8, name: 'Samsung 27" Monitor', image: '/Images/monitor.jpeg', price: '$319', rating: 4.4 },
        { id: 9, name: 'Samsung AC 1.5 Ton', image: '/Images/ac.png', price: '$1000', rating: 4.0 },
        { id: 10, name: 'Samsung Refrigerator 700L', image: '/Images/refr.jpeg', price: '$1200', rating: 4.5 },
        { id: 11, name: 'Samsung Microwave Oven', image: '/Images/oven.jpeg', price: '$150', rating: 4.3 },
        { id: 12, name: 'Samsung Bluetooth Speaker', image: '/Images/speaker.jpeg', price: '$80', rating: 4.2 }
    ],
    apple: [
      { id: 1, name: 'iPhone 15 Pro', image: '/Images/15pro.jpeg', price: '$999', rating: 4.8 },
      { id: 2, name: 'MacBook Air (M2, 2023)', image: '/Images/macbook air.jpeg', price: '$1099', rating: 4.1 },
      { id: 3, name: 'iPad Pro (12.9-inch, M2)', image: '/Images/ipad pro.jpeg', price: '$190', rating: 4.5 },
      { id: 4, name: 'Apple Watch Series 9', image: '/Images/watch 9.jpeg', price: '$9099', rating: 4.2 },
      { id: 5, name: 'AirPods Pro (2nd generation)', image: '/Images/airpods pro.jpeg', price: '$899', rating: 3.6 },
      { id: 6, name: 'iMac (24-inch, M1)', image: '/Images/imac.jpeg', price: '$789', rating: 4.1 },
      { id: 7, name: 'MacBook Pro (16-inch, M2 Max)', image: '/Images/macbook pro.jpeg', price: '$199', rating: 5.0 },
      { id: 8, name: 'Apple TV 4K', image: '/Images/apple tv.jpeg', price: '$569', rating: 3.6},
      { id: 9, name: 'HomePod (2nd generation)', image: '/Images/homepod.jpeg', price: '$9099', rating: 4.5},
      { id: 10, name: 'Magic Keyboard', image: '/Images/magickeyboard.jpeg', price: '$1099', rating: 4.3 },
      { id: 11, name: 'Apple Pencil (2nd generation)', image: '/Images/applepencil.png', price: '$7899', rating: 3.5},
      { id: 12, name: 'AirTag', image: '/Images/airtag.jpeg', price: '$2299', rating: 4.9 },

    ],
    huawei: [
      { id: 1, name: 'Huawei Mate 50 Pro', image: '/Images/1.jpeg', price: '$699', rating: 4.6 },
      { id: 2, name: 'Huawei P60 Pro', image: '/Images/2.jpeg', price: '$399', rating: 4.5 },
      { id: 3, name: 'Huawei MateBook X Pro 2023', image: '/Images/4.jpeg', price: '$499', rating: 4.2 },
      { id: 4, name: 'Huawei MatePad Pro 12.6', image: '/Images/4,.jpeg', price: '$999', rating: 4.3 },
      { id: 5, name: 'Huawei Watch GT 4', image: '/Images/5.jpeg', price: '$899', rating: 4.7 },
      { id: 6, name: 'Huawei FreeBuds Pro 2', image: '/Images/6.jpeg', price: '$699', rating: 3.5 },
      { id: 7, name: 'Huawei MateStation X', image: '/Images/7.jpeg', price: '$499', rating: 2.5 },
      { id: 8, name: 'Huawei Nova 11 Pro', image: '/Images/8.jpeg', price: '$299', rating: 5.0 },
      { id: 9, name: 'Huawei Vision S', image: '/Images/9.jpeg', price: '$999', rating: 3.5 },
      { id: 10, name: 'Huawei Mate X3', image: '/Images/10.jpeg', price: '$899', rating: 4.5 },
      { id: 11, name: 'Huawei Sound X', image: '/Images/11.jpeg', price: '$1299', rating: 4.9 },
      { id: 12, name: 'Huawei Watch Fit 2', image: '/Images/12.png', price: '$199', rating: 4.0 },

    ],
    infinix: [
        { id: 1, name: 'Infinix Zero Ultra', image: '/Images/1..jpeg', price: '$699', rating: 4.6 },
        { id: 2, name: 'Infinix Note 30 Pro', image: '/Images/2..jpeg', price: '$999', rating: 4.5 },
        { id: 3, name: 'Infinix Hot 30 5G', image: '/Images/3..jpeg', price: '$499', rating: 4.2 },
        { id: 4, name: 'Infinix Zero 20', image: '/Images/4..jpeg', price: '$999', rating: 4.3 },
        { id: 5, name: 'Infinix Note 12 VIP', image: '/Images/5..jpeg', price: '$899', rating: 4.7 },
        { id: 6, name: 'Infinix Smart 7', image: '/Images/6..jpeg', price: '$699', rating: 3.5 },
        { id: 7, name: 'Infinix Hot 12i', image: '/Images/7..jpeg', price: '$499', rating: 2.5 },
        { id: 8, name: 'Infinix Zero X Pro', image: '/Images/8..jpeg', price: '$299', rating: 5.0 },
        { id: 9, name: 'Infinix S5 Pro', image: '/Images/9..jpeg', price: '$999', rating: 3.5 },
        { id: 10, name: 'Infinix Note 10', image: '/Images/10..jpeg', price: '$899', rating: 4.5 },
        { id: 11, name: 'Infinix Hot 11 Play', image: '/Images/11..jpeg', price: '$1299', rating: 4.9 },
        { id: 12, name: 'Infinix Smart 6 HD', image: '/Images/12...jpeg', price: '$199', rating: 4.0 },
      ],
      hp: [
        { id: 1, name: 'HP Spectre x360 14', image: '/Images/1...jpeg', price: '$699', rating: 4.6 },
        { id: 2, name: 'HP Envy 13', image: '/Images/2...jpeg', price: '$999', rating: 4.5 },
        { id: 3, name: 'HP Pavilion Gaming Laptop', image: '/Images/3...jpeg', price: '$499', rating: 4.2 },
        { id: 4, name: 'HP Omen 16', image: '/Images/4...jpeg', price: '$999', rating: 4.3 },
        { id: 5, name: 'HP Elite Dragonfly G3', image: '/Images/5...jpeg', price: '$899', rating: 4.7 },
        { id: 6, name: 'HP ZBook Studio G9', image: '/Images/6...jpeg', price: '$699', rating: 3.5 },
        { id: 7, name: 'HP EliteBook 840 G9', image: '/Images/7...jpeg', price: '$499', rating: 2.5 },
        { id: 8, name: 'HP Chromebook x2 11', image: '/Images/8...jpeg', price: '$299', rating: 5.0 },
        { id: 9, name: 'HP Reverb G2 VR Headset', image: 'HP Reverb G2 VR Headset', price: '$999', rating: 3.5 },
        { id: 10, name: 'HP DeskJet Plus 4155', image: '/Images/10...jpeg', price: '$899', rating: 4.5 },
        { id: 11, name: 'HP Envy Inspire 7955e', image: '/Images/11...jpeg', price: '$1299', rating: 4.9 },
        { id: 12, name: 'HP Tango Smart Home Printer', image: '/Images/12....jpeg', price: '$199', rating: 4.0 },

      ],
      dell: [
        { id: 1, name: 'Dell XPS 15 9530', image: '/Images/1....jpeg', price: '$699', rating: 4.6 },
        { id: 2, name: 'Dell Inspiron 16 Plus', image: '/Images/2....jpeg', price: '$999', rating: 4.5 },
        { id: 3, name: 'Dell G15 Gaming Laptop', image: '/Images/3....jpeg', price: '$499', rating: 4.2 },
        { id: 4, name: 'Dell Latitude 9430', image: '/Images/4....jpeg', price: '$999', rating: 4.3 },
        { id: 5, name: 'Dell Precision 5570', image: '/Images/5....jpeg', price: '$899', rating: 4.7 },
        { id: 6, name: 'Dell Alienware m18', image: '/Images/6....jpeg', price: '$699', rating: 3.5 },
        { id: 7, name: 'Dell XPS 13 Plus', image: '/Images/7....jpeg', price: '$499', rating: 2.5 },
        { id: 8, name: 'Dell OptiPlex 3090', image: '/Images/8....jpeg', price: '$299', rating: 5.0 },
        { id: 9, name: 'Dell UltraSharp 32 4K USB-C Hub Monitor', image: '/Images/9....jpeg', price: '$999', rating: 3.5 },
        { id: 10, name: 'Infinix Note 10', image: '/Images/10....jpeg', price: '$899', rating: 4.5 },
        { id: 11, name: 'Infinix Hot 11 Play', image: '/Images/11....jpeg', price: '$1299', rating: 4.9 },
        { id: 12, name: 'Infinix Smart 6 HD', image: '/Images/12.....jpeg', price: '$199', rating: 4.0 },
      ],
      vivo: [
        { id: 1, name: 'Vivo X90 Pro+', image: '/Images/1.....jpeg', price: '$699', rating: 4.6 },
        { id: 2, name: 'Vivo V29 Pro', image: '/Images/2.....jpeg', image: '/Images/3....jpeg', price: '$499', rating: 4.2 },
        { id: 3, name: 'Vivo Y78 5G', image: '/Images/3.....jpeg', price: '$499', rating: 4.2 },
        { id: 4, name: 'Vivo X Fold+', image: '/Images/4.....jpeg', price: '$999', rating: 4.3 },
        { id: 5, name: 'Vivo S17 Pro', image: '/Images/5.....jpeg', price: '$899', rating: 4.7 },
        { id: 6, name: 'Vivo T2 5G', image: '/Images/6.....jpeg', price: '$699', rating: 3.5 },
        { id: 7, name: 'Vivo V27e', image: '/Images/7.....jpeg', price: '$499', rating: 2.5 },
        { id: 8, name: 'Vivo Y100A', image: '/Images/8.....jpeg', price: '$299', rating: 5.0 },
        { id: 9, name: 'Vivo NEX 3S 5G', image: '/Images/9.....jpeg', price: '$999', rating: 3.5 },
        { id: 10, name: 'Vivo V23 5G', image: '/Images/10.....jpeg', price: '$899', rating: 4.5 },
        { id: 11, name: 'Vivo iQOO 11', image: '/Images/11.....jpeg', price: '$1299', rating: 4.9 },
        { id: 12, name: 'Vivo Y36', image: '/Images/12......jpeg', price: '$199', rating: 4.0 },
        
      ],
      lenovo: [
        { id: 1, name: 'Lenovo ThinkPad X1 Carbon Gen 11', image: '/Images/1......jpeg', price: '$699', rating: 4.6 },
        { id: 2, name: 'Lenovo Yoga 9i (14”, 8th Gen)', image: '/Images/2......jpeg', price: '$999', rating: 4.5 },
        { id: 3, name: 'Lenovo Legion 5 Pro Gen 7', image: '/Images/3......jpeg', price: '$499', rating: 4.2 },
        { id: 4, name: 'Lenovo IdeaPad 5 Pro Gen 7', image: '/Images/4......jpeg', price: '$999', rating: 4.3 },
        { id: 5, name: 'Lenovo Tab P12 Pro', image: '/Images/5......jpeg', price: '$899', rating: 4.7 },
        { id: 6, name: 'Lenovo Smart Clock 2', image: '/Images/6......jpeg', price: '$699', rating: 3.5 },
        { id: 7, name: 'Lenovo ThinkBook 14s Yoga', image: '/Images/7......jpeg', price: '$499', rating: 2.5 },
        { id: 8, name: 'Lenovo Yoga Slim 7i Pro X', image: '/Images/8......jpeg', price: '$299', rating: 5.0 },
        { id: 9, name: 'Lenovo ThinkCentre M70a', image: '/Images/9......jpeg', price: '$999', rating: 3.5 },
        { id: 10, name: 'Lenovo ThinkVision M14', image: '/Images/10......jpeg', price: '$899', rating: 4.5 },
        { id: 11, name: 'Lenovo Legion Phone Duel 2', image: '/Images/11......jpeg', price: '$1299', rating: 4.9 },
        { id: 12, name: 'Lenovo Ideapad Flex 5', image: '/Images/12.......jpeg', price: '$199', rating: 4.0 },

     
      ],

  };
  